# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Logistica Guru"
license = "MIT"
licenselink = "https://github.com/kishaningithub/hugo-creative-portfolio-theme/blob/master/LICENSE"
description = "Bootstrap 4 with masonry using CSS. Insipered in Wired"
homepage = "https://logistica.guru"
tags = ["projects", "minimal", "responsive"]
features = ["bootstrap", "responsive", "google analytics"]
min_version = 0.20

[author]
  name = "Johnatas Montezuma"
  homepage = "https://github.com/johnatasjmo"
  