baseurl = "/"
title = "Logistica Guru"
theme = "hugo-logistica-guru"
languageCode = "es"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-109487588-1"
paginate = 12

# Set the followings to true as part of your site SEO
enableRobotsTXT = true
canonifyURLs = true

pluralizelisttitles= false


[taxonomies]
  tag = "tags"

[params]
  style = "default"
  description = "Noticias y educacion sobre logistica y cadena de suministro"
  copyright = "Logistica Guru"
  sidebarAbout = [""]

  email = "jmo@logisticsmaven.com"

  # Nav links
  [[params.navlinks]]
  name = "Noticias"
  url = "/noticias/"
  home = true
  weight = 1

  [[params.navlinks]]
  name = "Supply Chain"
  url = "/supplychain/"
  home = true
  weight = 2

  [[params.navlinks]]
  name = "Logistica"
  url = "/logistica/"
  home = true
  weight = 3

  [params.social]
  facebook      = ""
  googleplus    = ""
  email         = "jmo@logisticsmaven.com"
  twitter       = "https://twitter.com/logisticaguru"
  linkedin      = ""
  stackoverflow = ""
  instagram     = ""
  github        = ""
  youtube       = ""
  whatsapp      = ""
