backend:
  name: github
  repo: johnatasjmo/logisticaguru # Path to your Github repository
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

media_folder: "static/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "docs" # Used in routes, e.g., /admin/collections/blog
    label: "Documentacion" # Used in the UI
    folder: "content/docs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Show Image", name: "showonlyimage", widget: "hidden", default: "true"}
      - {label: "Tags", name: "tags", widget: "select", options: ["front", "docs", "transporte"], multiple: true, default: ["front"]}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "noticias" # Used in routes, e.g., /admin/collections/blog
    label: "Noticias" # Used in the UI
    folder: "content/noticias" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}